### ISSUE TITLE
Not functional in paths with spaces

### ISSUE THREAD

**Issue by crstauf** [gregorym/atom-inline-blame#14]
When the project path contains a space, console contains `fatal: bad revision` error.

Discovered in https://github.com/gregorym/atom-inline-blame/issues/7#issuecomment-636416485.

**Comment by crstauf** [comment]
> The file path needs to be wrapper in " " to handle path with spaces.

@gregorym What does that mean? I can fix myself? How?

**Comment by gregorym** [comment]
This is now fixed in version `0.0.9`

**Comment by crstauf** [comment]
Thanks, @gregorym! Especially for the nifty little package that I enjoy so very much!
