### ISSUE TITLE
Startup time is very high

### ISSUE THREAD

**Issue by adityavm** [gregorym/atom-inline-blame#2]
The startup time for `atom-inline-blame` is very high (it fluctuates between 200ms - 900ms) when it most probably shouldn't be. Maybe there should be some kind of delayed activation?

**Comment by gregorym** [comment]
How did you measure that?

**Comment by adityavm** [comment]
@gregorym [atom-timecop](https://atom.io/packages/timecop)

**Comment by adityavm** [comment]
On further investigation, the fluctuation seems to be only when the package changes (probably because of some kind of cache invalidation + recaching).

Activation time when not changing the package seems to be consistent around 120ms, which is still high, but not _very_ high.

Some times for reference:
<img width="256" alt="screen shot 2018-04-22 at 8 05 07 am" src="https://user-images.githubusercontent.com/80849/39090703-ed30c1e2-4603-11e8-9773-f19503ee48bf.png">

**Comment by adityavm** [comment]
💪 

<img width="254" alt="screen shot 2018-04-22 at 9 55 09 am" src="https://user-images.githubusercontent.com/80849/39091536-4dfc94d8-4613-11e8-9e10-76f5c942c90c.png">

i'm going to test this out over 24 hours under work conditions and submit a PR

**Comment by gregorym** [comment]
Cool. Curious to see what the culprit was

**Comment by adityavm** [comment]
Everything was (effectively) synchronous and listening for everything. I've made things a lot more selective. The commit is here https://github.com/adityavm/atom-inline-blame/commit/7c6bc5666f58d95216089bd124aed59212a7a1a0
